Repository Glovo/foodi-ml-dataset, pull requests merged in 2021-09, with the labels that each got.

#5 Fix two auxiliary stores, renamed collection
  README.md
  notebooks/FooDI-ML Dataset Stats Analytics.ipynb
Labels: size/XL

#6 feat: add hash images script
  scripts/hash_images.py
Labels: size/S

#11 fix:link in readme
  README.md
Labels: size/XS

#12 optimisation:remove unused objects and more
  benchmarks/adapt/retrieval/model/similarity/similarity.py
  benchmarks/adapt/retrieval/train/evaluation.py
Labels: size/S
